In [19]:
from scipy.stats import multivariate_normal
import numpy as np
mean=[5.4 ,2.4, 3.2]
cov=[[ 24.3, -16.2 ,-21.599998],
 [-16.2, 10.800001 , 14.4 ],
 [-21.599998,14.4, 19.199999]]


cov = np.round(cov, 4)
mv_gaussian = multivariate_normal(mean=mean,
                                  cov=cov,
                                  allow_singular=True)

print(cov)

[[ 24.3 -16.2 -21.6]
 [-16.2  10.8  14.4]
 [-21.6  14.4  19.2]]
